version: "3.8"
services:
  cups:
    image: lemariva/rpi-cups
    ports:
      - 631:631
    volumes:
      - /var/run/dbus:/var/run/dbus
      - /dev/bus/usb:/dev/bus/usb
    privileged: true
    restart: unless-stopped
